Ensure hosts cannot be in automationcontroller/execution_nodes groups
sarabrajsingh/awx pull request #1
Opened 2021-07-29 16:31 UTC by tchellomello

```ini
[automationcontroller]
controllerA.tatu.home   peers=storm.tatu.home node_type=control
controllerB.tatu.home   peers=p50.tatu.home,storm.tatu.home  node_type=control
controllerC.tatu.home   
p90.tatu.home     ansible_host=192.168.111.90   # no peers

[automationcontroller:vars]
node_type=hybrid

### receptor execution plane nodes
[execution_nodes]
storm.tatu.home   ansible_host=192.168.111.36   peers=execution_nodes
p70.tatu.home     ansible_host=192.168.111.33   peers=p50.tatu.home,storm.tatu.home
t470n1.tatu.home  ansible_host=192.168.111.34   peers=EastCoastNodes
t470n2.tatu.home  ansible_host=192.168.111.35   peers=controllerC.tatu.home
p50.tatu.home     ansible_host=192.168.111.50   peers=p90.tatu.home
p90.tatu.home     ansible_host=192.168.111.90   # no peers
controllerC.tatu.home  
```

```python
(py39) [mdemello@storm REDHAT]$ ansible-playbook  -i inventory  generate_mesh.yml 

PLAY [Generate mesh] ****************************************************************************************************************************

TASK [parse mesh] *******************************************************************************************************************************
fatal: [p50.tatu.home]: FAILED! => {"msg": "The following hosts cannot be members of both [automationcontroller] and [execution_nodes] groups: p90.tatu.home, controllerC.tatu.home"}

NO MORE HOSTS LEFT ******************************************************************************************************************************

PLAY RECAP **************************************************************************************************************************************
p50.tatu.home              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

2021-07-29 18:57 UTC, sarabrajsingh requested changes

2021-07-29 18:57 UTC, sarabrajsingh commented on awx_collection/plugins/action/generate_mesh.py
> +EXECUTION_NODE_TYPES = ['execution', 'hop']
move lines 11 and 12 inside the class definition and leverage the `frozenset` datatype to make these lists immutable , private and constant.

ie. 

`_CONTROLLER_NODE_TYPES = frozenset(('control', 'hybrid'))`

this will align us with other ansible-devel code for plugins :)

2021-07-29 21:09 UTC, tchellomello commented on awx_collection/plugins/action/generate_mesh.py
> +EXECUTION_NODE_TYPES = ['execution', 'hop']
Thanks!

2021-07-30 15:38 UTC, sarabrajsingh approved these changes

2021-07-30 15:41 UTC, sarabrajsingh approved these changes

2021-07-30 15:41 UTC, merged