Created a basic documentation module to go along with our action plugin
sarabrajsingh/awx pull request #2
Opened 2021-08-02 15:46 UTC by jbradberry

##### SUMMARY

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

 - API
 - UI

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2021-08-02 15:52 UTC, AlanCoding commented
This modifies https://github.com/ansible/awx/pull/10779

2021-08-02 16:02 UTC, AlanCoding commented on awx_collection/plugins/modules/generate_mesh.py
> +  - This module inspects the inventory hosts for receptor nodes, expands out the list of
People reading this will not know what inventory is expected. An appropriate link to disambiguate this would be something like this:

https://docs.ansible.com/ansible-tower/latest/html/installandreference/tower_install_wizard.html#setting-up-the-inventory-file

Up until this point, this collection has only interacted with the AWX API.

Unlike other modules in the collection, this will not require authentication to the API. Correct me if I'm wrong, but it also doesn't require actual SSH access to any of those nodes. This is doing stuff based exclusively based on the (yet unpublished) "setup" inventory structure.

2021-08-02 17:22 UTC, jbradberry commented on awx_collection/plugins/modules/generate_mesh.py
> +  - This module inspects the inventory hosts for receptor nodes, expands out the list of
> Up until this point, this collection has only interacted with the AWX API.
> 
> Unlike other modules in the collection, this will not require authentication to the API. Correct me if I'm wrong, but it also doesn't require actual SSH access to any of those nodes. This is doing stuff based exclusively based on the (yet unpublished) "setup" inventory structure.

That is correct.  Do you think there is some other collection that would make more sense to add these to?

2021-08-02 19:05 UTC, AlanCoding commented on awx_collection/plugins/modules/generate_mesh.py
> +  - This module inspects the inventory hosts for receptor nodes, expands out the list of
Probably not, because the platform collection won't be very accessible. I'm fine to introduce the setup inventory file here, because what it's doing is very self-contained.

2021-08-03 17:11 UTC, sarabrajsingh requested changes

2021-08-03 17:11 UTC, sarabrajsingh commented on awx_collection/plugins/modules/calculate_mesh.py
> +    dump_graph: /foo/bar/baz.dot
name `dump_graph` to `generate_dot_file`

2021-08-03 17:23 UTC, jbradberry commented on awx_collection/plugins/modules/calculate_mesh.py
> +  dump_graph:
... I accidentally saved to a stale filename.  This change _is_ in here, I just need to reconcile the two files :face_with_head_bandage:

2021-08-03 18:11 UTC, sarabrajsingh approved these changes

2021-08-03 18:11 UTC, merged